### PR TITLE
Fix FFI subdirectory build

### PR DESCRIPTION
**Pull request by mtzguido**
Just adding the `MiTLS_` prefix to each file. Also, for the OCaml files here, I changed the prefix for `MiTLS.` to `MiTLS_`.

### CODE REVIEW

**Comment by mtzguido** [comment]
Updated. I had missed updating the header and the linker script. This passed a local build, but I'll try a full everest build from a clean slate, and merge if that works.

**Comment by mtzguido** [comment]
This works. But given the external names changed it'd be good to get some confirmation that it's ok... maybe @ad-l ?

**Comment by msprotz** [comment]
Let's merge and unblock the build, we can always finesse later. Thanks Guido!!

**Comment by mtzguido** [comment]
We probably need https://github.com/hacl-star/merkle-tree/pull/16 too (I cannot merge it).

**Pull request merged**
