### PR TITLE
Prefix all module names with MiTLS.

### PR DESCRIPTION
**Pull request by gebner**
This PR moves all source files into the `MiTLS.` namespace.  For the upcoming dataset release, we want to avoid a situation where two projects have a source file with the same name---that allows us to put all F* files in the same directory and avoid complicated include path configuration.  In this case, both HACL* and MiTLS have a `Mem.fst` file.  Adding the `MiTLS.` prefix avoids this clash.

Most of the changes have been made automatically using regexes.  Both extraction and the `make test` pass.

The only unexpected complication is in the HKDF and HMAC modules, where extraction failed after adding the prefix.  Both of these files assume that the (secret) `uint8` type from HACL* is actually `UInt8.t`.  They used to do this by opening the `Declassify` module (which contains `uint8 == UInt8.t` as a lemma).  After the name change, Karamel started adding a `<: any` cast to the allocation code in those modules.  Instead of `uint8_t` the C code contains `void *` (which means it no longer compiles because you can't implicitly convert between `uint8_t *` and `void **`).

I have worked around this by opening the `Lib.IntTypes` module in HKDF/HMAC instead (thus exposing the implementation of `uint8` directly).  This seems to make Karamel happy again.  (I have also added interface files for HKDF/HMAC to avoid transitively exposing the `uint8` implementation, but I believe that's a good idea regardless.)  Unfortunately, I haven't been able to create a self-contained example reproducing this issue.

### CODE REVIEW

**Comment by msprotz** [comment]
FYI, you can probably debug this without krml by extracting to OCaml. The `<: any` will show up as an Obj.magic, meaning that F* could not type-check the erased code as fitting within ML. I would indeed suspect a missing type equation, especially seeing that miTLS extract without --cmi.

**Comment by nikswamy** [comment]
heads up @fournet @ad-l

**Comment by ad-l** [comment]
This looks OK to me, thanks for your work @gebner

**Comment by gebner** [comment]
> I would indeed suspect a missing type equation, especially seeing that miTLS extract without --cmi.

Thank you so much for this pointer!  I have finally realized what was going on.  Not all parts of miTLS are extracted without `--cmi`, three modules are/were compiled with cross-module inlining enabled:
```
# ...
$(EXTRACT_DIR)/Hashing.krml \
$(EXTRACT_DIR)/HMAC.krml \
$(EXTRACT_DIR)/HKDF.krml\
$(EXTRACT_DIR)/Lib_IntTypes.krml\
: CMI = --cmi
```

Sorry, I completely missed this makefile.

**Pull request merged**
